/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_2d83519f (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/ewsehvgwzczlshyoyhqf/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL") || "https://ewsehvgwzczlshyoyhqf.supabase.co",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_ANON_KEY") || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3c2Vodmd3emN6bHNoeW95aHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxMTA2MjIsImV4cCI6MjA5OTY4NjYyMn0.kWqk1d-8mNt3mG5zwfaRC9RUgZt7WgEyRNrqn7frn-s",
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    const supabase = client()
    const { error } = await supabase.from("kv_store_2d83519f").upsert({
      key,
      value
    });
    if (error) {
      console.warn("KV set warning:", error.message);
    }
  } catch (e) {
    console.warn("KV set exception:", e);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_2d83519f").select("value").eq("key", key).maybeSingle();
    if (error || !data) {
      return null;
    }
    return data.value;
  } catch (e) {
    console.warn("KV get exception:", e);
    return null;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  try {
    const supabase = client()
    const { error } = await supabase.from("kv_store_2d83519f").delete().eq("key", key);
    if (error) {
      console.warn("KV del warning:", error.message);
    }
  } catch (e) {
    console.warn("KV del exception:", e);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  try {
    const supabase = client()
    const { error } = await supabase.from("kv_store_2d83519f").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    if (error) {
      console.warn("KV mset warning:", error.message);
    }
  } catch (e) {
    console.warn("KV mset exception:", e);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_2d83519f").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_2d83519f").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix (returns values only).
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_2d83519f").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Search for key-value pairs by prefix (returns full key-value entries).
export const getByPrefixEntries = async (prefix: string): Promise<{ key: string; value: any }[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_2d83519f").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data ?? [];
};